apiVersion: v1
description: Cluster Profile Manager
name: cluster-profile-manager
version: v2024.11.18
appVersion: v0.3.0
home: https://github.com/kluster-manager/cluster-profile
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kluster-manager/cluster-profile
maintainers:
- name: appscode
  email: support@appscode.com
