apiVersion: v1
description: Cluster Auth Agent
name: cluster-auth-agent
version: v2026.2.16
appVersion: v0.5.0
home: https://github.com/kluster-manager/cluster-auth
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/kluster-manager/cluster-auth
maintainers:
- name: appscode
  email: support@appscode.com
