properties:
  addons:
    properties:
      cluster-proxy:
        properties:
          enabled:
            type: boolean
        required:
        - enabled
        type: object
      kubeslice:
        properties:
          enabled:
            type: boolean
          values:
            properties:
              networkInterface:
                type: string
              projectNamespace:
                type: string
            required:
            - networkInterface
            - projectNamespace
            type: object
        required:
        - enabled
        - values
        type: object
    required:
    - cluster-proxy
    - kubeslice
    type: object
  fullnameOverride:
    type: string
  nameOverride:
    type: string
required:
- addons
type: object
