apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: hub-cluster-robot
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: hub-cluster-robot
