apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.gateway.open-cluster-management.io
  labels:
    api: cluster-extension-apiserver
    apiserver: "true"
spec:
  version: v1alpha1
  group: gateway.open-cluster-management.io
  groupPriorityMinimum: 2000
  service:
    name: gateway-service
    namespace: {{ .Release.Namespace }}
    port: 9443
  versionPriority: 10
  insecureSkipTLSVerify: true