apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccount: cluster-gateway
      volumes:
        - name: proxy-client
          secret:
            secretName: proxy-client
        - name: proxy-server-ca
          secret:
            secretName: proxy-server-ca
      containers:
        - name: gateway
          image: {{ .Values.image }}:{{ .Values.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          args:
            - --secure-port=9443
            {{ if .Values.clusterProxy.enabled }}
            - --proxy-host={{ .Values.clusterProxy.endpoint.host }}
            - --proxy-port={{ .Values.clusterProxy.endpoint.port }}
            - --proxy-ca-cert=/etc/ca/ca.crt
            - --proxy-cert=/etc/tls/tls.crt
            - --proxy-key=/etc/tls/tls.key
            {{ end }}
            - --feature-gates={{ if .Values.featureGate.healthiness }}HealthinessCheck=true,{{ end }}
            # TODO: certificate rotation, otherwise the self-signed will expire in 1 year
          {{ if .Values.clusterProxy.enabled }}
          volumeMounts:
            - name: proxy-client
              mountPath: "/etc/tls/"
              readOnly: true
            - name: proxy-server-ca
              mountPath: "/etc/ca/"
              readOnly: true
            {{ end }}
          ports:
            - containerPort: 9443
