apiVersion: v2
name: cluster-manager-hub
description: A Helm chart for Open Cluster Manager Hub
type: application
version: v2026.2.16
appVersion: v1.2.0
home: https://open-cluster-management.io
sources:
- https://github.com/kluster-manager/installer
maintainers:
- name: appscode
  email: support@appscode.com
